### ISSUE TITLE
Should the generator map dict to object?

### ISSUE THREAD

**Issue by cmendible** [shaded-enmity/ansible-schema-generator#1]
Hi @shaded-enmity according to this: https://github.com/ansible/ansible/pull/42033#pullrequestreview-132918155 I had to change the documentation to use `dict` instead of `object`. 

Current code does not map the `dict` type:

```
TYPE_MAP = {
        'int': {'$ref': '#/definitions/ansible_number'},
        'bool': {'$ref': '#/definitions/ansible_truth'},
        'str': 'string',
        'float': 'number',
        'object': 'object'
    }
```

Is that the place to fix it? If so I can create a PR for it.

**Comment by shaded-enmity** [comment]
Hello @cmendible yes, thanks for looking into this, PR will be appreciated.

**Comment by cmendible** [comment]
Closing since https://github.com/shaded-enmity/ansible-schema-generator/pull/2 was merged.
