### ISSUE TITLE
Error on apt: name=[list]

### ISSUE THREAD

**Issue by zoredache** [shaded-enmity/ansible-schema-generator#4]
> https://docs.ansible.com/ansible/latest/modules/apt_module.html#parameters
> name: A **list** of package names,

This is perfectly valid ansible

    - name: install packages
      apt:
        name:
        - foo
        - bar

But this results in errors, since the schema is reporting that 'name' should be a string.

**Comment by shaded-enmity** [comment]
Thanks for the report @zoredache I should have new schemas today where this will be fixed.

EDIT: https://github.com/SchemaStore/schemastore/pull/543

**Comment by shaded-enmity** [comment]
Closing the issue, if there are still problems with this please open a new one.
